export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Add CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight request
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  try {
    const { history, systemInstruction } = req.body;

    // Validate request body
    if (!history || !systemInstruction) {
      return res.status(400).json({ 
        error: 'Missing required fields: history and systemInstruction' 
      });
    }

    // Check for API key
    if (!process.env.GEMINI_API_KEY) {
      console.error('GEMINI_API_KEY is not set in environment variables');
      return res.status(500).json({ 
        error: 'API key not configured. Please set GEMINI_API_KEY in Vercel environment variables.' 
      });
    }

    // Transform history to ensure correct role mapping
    const transformedHistory = history.map(msg => ({
      role: msg.role === 'streaming_model' ? 'model' : msg.role,
      parts: msg.parts
    }));

    const payload = {
      contents: transformedHistory,
      systemInstruction: {
        parts: [{ text: systemInstruction }]
      }
    };

    console.log('Sending request to Gemini API...');
    
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { 
          "Content-Type": "application/json"
        },
        body: JSON.stringify(payload),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API Error Response:', errorText);
      return res.status(response.status).json({ 
        error: `Gemini API error: ${response.status} - ${errorText}` 
      });
    }

    const json = await response.json();

    // Check for blocked content or other issues
    if (json.promptFeedback?.blockReason) {
      return res.status(400).json({ 
        error: `Content blocked: ${json.promptFeedback.blockReason}` 
      });
    }

    // Extract reply
    const reply =
      json?.candidates?.[0]?.content?.parts?.[0]?.text ||
      "No response generated by Gemini.";

    return res.status(200).json({ reply });

  } catch (err) {
    console.error("GEMINI API ERROR:", err);
    return res.status(500).json({ 
      error: err.message || 'Internal server error' 
    });
  }
}