export default async function handler(req, res) {
  try {
    const { history, systemInstruction } = req.body;

    const response = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" +
        process.env.GEMINI_API_KEY,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: history,
          systemInstruction: {
            parts: [{ text: systemInstruction }],
          },
        }),
      }
    );

    const json = await response.json();

    // Gemini returns text in candidates array
    const reply =
      json?.candidates?.[0]?.content?.parts?.[0]?.text ||
      "No response generated by Gemini.";

    res.status(200).json({ reply });
  } catch (err) {
    console.error("GEMINI API ROUTE ERROR:", err);
    res.status(500).json({ error: err.message });
  }
}
